import ProvidersRedux from "@/store/Providers";
import { Inter } from 'next/font/google';
import { ToastContainer } from "react-toastify";
import "./globals.css";
import { Providers } from "./providers";
const inter = Inter({
  weight: '400',
  subsets: ['latin'],
})
export const metadata = {
  title: "E-learning",
  description: "Generated by E-learning",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={inter.className}>
        <Providers>
          <ProvidersRedux>
            {children}
          </ProvidersRedux>
        </Providers>
        <ToastContainer />
      </body>
    </html>
  );
}
