import { Inter } from 'next/font/google'
import ProvidersRedux from "@/store/Providers";
import { Providers } from "./providers";
import "./globals.css";
const inter = Inter({
  weight: '400',
  subsets: ['latin'],
})
export const metadata = {
  title: "E-learning",
  description: "Generated by E-learning",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={inter.className}>
        <Providers>
          <ProvidersRedux>
            {children}
          </ProvidersRedux>
        </Providers>
      </body>
    </html>
  );
}
